using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class MUI_Monitor : MonoBehaviour {

    //RA捌セ
    public static MUI_Monitor script;
    //把计菏北Dictionary
    public static Dictionary<string,float> MonitorDictionary = new Dictionary<string,float>();

    public Vector2 From;
    public Vector2 To;
    public string Key;

    public Vector2 Percentage;

    [HideInInspector]
    public MUI_Enum.MUIType MUI_Type;

    public bool dump;
	// Use this for initialization
	void Start () {
        script = this;
	}
	
	// Update is called once per frame
	void Update () {

        if(dump)
        {
            DumpAll();
                dump = false;
        }
	}


    /// <summary>
    /// 块X场戈T
    /// </summary>
    public void DumpAll()
    {
        foreach (var md in MonitorDictionary)
            print("KeyG" + md.Key + "ValueG" + md.Value);
    }

    /// <summary>
    /// O_sb
    /// </summary>
    /// <param name="key">Keyr</param>
    /// <returns></returns>
    public bool isValid(string key)
    {
        if (MonitorDictionary.ContainsKey(key))
            return true;
        else
            return false;
    }

    /// <summary>
    /// o计
    /// </summary>
    /// <param name="key">Keyr</param>
    /// <returns></returns>
    public float GetValue(string key)
    {
        if (MonitorDictionary.ContainsKey(key))
            return MonitorDictionary[key];
        else
            return 0;
    }

    /// <summary>
    /// ]w计
    /// </summary>
    /// <param name="key">Keyr</param>
    /// <param name="newValue">N杭骗</param>
    public void SetValue(string key , float newValue)
    {
        if (MonitorDictionary.ContainsKey(key))
            MonitorDictionary[key] = newValue;
    }

}
